<html>
    <head>
        <script src="https://www.hipchat.com/atlassian-connect/all.js"></script>
        <link rel="stylesheet" href="https://www.hipchat.com/atlassian-connect/all.css" />
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous" />
        <style>
            #screen_name,#webhook_trigger {
                max-width: 250px;
            }
        </style>
    </head>
    <body>
        <form method="POST">
            <?php if (isset($errors) && count($errors)): ?>
            <div class="alert alert-danger">
                <ul><?php foreach ($errors as $elementName => $subErrors): ?>
                    <?php foreach ($subErrors as $error): ?>
                        <li><strong><?= $elementName ?>:</strong> <?= $error ?></li>
                    <?php endforeach; ?>
                <?php endforeach; ?></ul>
            </div>
            <?php endif; ?>
            <?php if (isset($success) && $success): ?>
            <div class="alert alert-success">
                <?= $success ?>
            </div>
            <?php endif; ?>
            <div class="form-group">
                <label for="screen_name">Twitter Screen Name (without @)</label>
                <input name="screen_name" id="screen_name" class="form-control" placeholder="BoredElonMusk" type="text" maxlength="50" value="<?= $screen_name ?>"?>
            </div>
            <div class="form-group">
                <label for="webhook_trigger">Web Hook Trigger (Example: /tq):</label>
                <input name="webhook_trigger" id="webhook_trigger" class="form-control" placeholder="/elon" type="text" maxlength="50" value="<?= $webhook_trigger ?>"?>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
            <input type="hidden" name="<?= $csrf_nameKey ?>" value="<?= $csrf_name ?>">
            <input type="hidden" name="<?= $csrf_valueKey ?>" value="<?= $csrf_value ?>">
        </form>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>