<html>
    <head>
        <script src="https://www.hipchat.com/atlassian-connect/all.js"></script>
        <link rel="stylesheet" href="https://www.hipchat.com/atlassian-connect/all.css">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
        </head>
    <body>
        <form method="POST">
            <div>
                <label for="screen_name">Twitter Screen Name:</label>
                <input name="screen_name" id="screen_name" type="text" maxlength="50" value="<?= $screen_name ?>"?>
            </div>
            <div>
                <label for="webhook_trigger">Web Hook Trigger (Example: /tq):</label>
                <input name="webhook_trigger" id="webhook_trigger" type="text" maxlength="50" value="<?= $webhook_trigger ?>"?>
            </div>
            <div>
                <input type="submit" value="Save" />
            </div>
            <input type="hidden" name="<?= $csrf_nameKey ?>" value="<?= $csrf_name ?>">
            <input type="hidden" name="<?= $csrf_valueKey ?>" value="<?= $csrf_value ?>">
        </form>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>